name: Deploy to Production
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu || exit 1
            if [ -d "cdchr" ]; then
              cd cdchr
              git reset --hard
              git clean -fd
              git pull origin main
            else
              git clone https://github.com/neel2751/cdchr.git cdchr
              cd cdchr
            fi
            npm install
            npm run build
            pm2 restart next-app || pm2 start npm --name "next-app" -- start
            pm2 save
